<?php
// +----------------------------------------------------------------------
// | @date: 2018/5/28 - 17:00
// +----------------------------------------------------------------------
// | @author：weipinglee
// +----------------------------------------------------------------------
// | @desc：
// +----------------------------------------------------------------------
namespace app\admin\Controller;

use think\Request;
class Config extends Base
{

    protected $serviceModel = null;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->serviceModel = \think\Loader::model('Config','service');
        $this->view->engine->layout('layout/layout');
    }


    public function edit()
    {
        $request = Request::instance();
        if($request->isPost()){
            $id = 1;
            $data = $request->param();
            $update = array('overdue_days'=>$data['days']);
            $res = $this->serviceModel->edit($id,$update);
            die(json_encode($res));
        }elseif($request->isGet()){
            $id = 1;
            $data = $this->serviceModel->row($id);
            $this->assign('data',$data);
            return $this->fetch();
        }

    }

}