<?php
/**
 * Created by PhpStorm.
 * User: weipinglee
 * Date: 2018/5/25
 * Time: 10:10
 */

namespace app\admin\Controller;
use think\Request;

class Person extends Base{

    protected $serviceModel = null;
    protected $model = null;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->serviceModel = \think\Loader::model('Person','service');
        $this->model = \think\Loader::model('Person','model');
        $this->view->engine->layout('layout/layout');
    }

    public function lst()
    {
        $request = Request::instance();
        $model = $this->serviceModel;
        $page = isset($_GET['page']) ? $_GET['page'] : 1 ;
        $name = $request->param('name');
        $mobile = $request->param('mobile');
        $where = '';
        if($name){
            $where .=  ' AND name like "%'.$name.'%"';
        }
        if($mobile){
            $where .= ' AND mobile like "%'.$mobile.'%"';
        }
        $data = $model->lists($page,$where);
        $this->assign(
            'data',$data['data']
        );
        $this->assign('pageData',$data['page']);

        // 设置页面中的信息
        $this->assign(array(
            '_page_btn_name' => '添加人员',
            '_page_btn_link' => url('add'),
        ));

        $this->assign('search',$this->model->searchFields());
        return $this->fetch();
    }
    public function add()
    {
        $request = Request::instance();
        if($request->isPost()){
            //print_r($request->param());
            $res = $this->serviceModel->add($request->param());
            die(json_encode($res));
        }elseif($request->isGet()){
            return $this->fetch();
        }


    }
    public function edit()
    {
        $request = Request::instance();
        if($request->isPost()){
            $id = $request->param('id');
            $data = $request->param();
            $res = $this->serviceModel->edit($id,$data);
            die(json_encode($res));
        }elseif($request->isGet()){
            $id = $request->param('id');
            $data = $this->serviceModel->row($id);
            $this->assign('data',$data);
            return $this->fetch();
        }

    }
    public function delete()
    {
        $request = Request::instance();
        $res = $this->serviceModel->del($request->param('id'));
        die(json_encode($res));
    }




}
