<?php
/**
 * Created by PhpStorm.
 * User: weipinglee
 * Date: 2018/5/25
 * Time: 10:10
 */

namespace app\admin\Controller;
use think\Request;

class PersonBank extends Base{

    protected $serviceModel = null;
    protected $model = null;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->serviceModel = \think\Loader::model('PersonBank','service');
        $this->model = \think\Loader::model('PersonBank','model');
        $this->view->engine->layout('layout/layout');
    }

    public function lst()
    {
        $request = Request::instance();
        $model = $this->serviceModel;
        $page = isset($_GET['page']) ? $_GET['page'] : 1 ;
        $person_id = $request->param('person_id');
       $where = '';
       $bind = array();
       if($person_id){
           $where .= ' AND b.person_id=:person_id';
           $bind = array('person_id'=>$person_id);
       }
        $data = $model->lists($page,$where,$bind);
        $this->assign(
            'data',$data['data']
        );
        $this->assign('pageData',$data['page']);

        // 设置页面中的信息
        $this->assign(array(
            '_page_btn_name' => '添加银行账户',
            '_page_btn_link' => url('add',array('person_id'=>$person_id))
        ));

        return $this->fetch();
    }
    public function add()
    {
        $request = Request::instance();
        if($request->isPost()){
            //print_r($request->param());
            $res = $this->serviceModel->add($request->param());
            die(json_encode($res));
        }elseif($request->isGet()){
            $person_id = $request->param('person_id');
            if($person_id){
                $personModel = \think\Loader::model('Person','service');
                $personData = $personModel->data($person_id);
                $this->assign('personData',$personData);
            }
            $this->assign('person_id',$person_id);

            return $this->fetch();
        }


    }
    public function edit()
    {
        $request = Request::instance();
        if($request->isPost()){
            $id = $request->param('id');
            $data = $request->param();
            $res = $this->serviceModel->edit($id,$data);
            die(json_encode($res));
        }elseif($request->isGet()){
            $id = $request->param('id');
            $data = $this->serviceModel->data($id);
            $this->assign('data',$data);
            return $this->fetch();
        }

    }
    public function delete()
    {
        $request = Request::instance();
        $res = $this->serviceModel->delete($request->param('id'));
        die(json_encode($res));
    }




}
