<?php
/**
 * Created by PhpStorm.
 * User: weipinglee
 * Date: 2018/5/25
 * Time: 10:10
 */

namespace app\admin\Controller;
use think\Request;

class Person extends Base{

    protected $eventCtr = null;
    protected $model = null;
    protected $dataController = null;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->model = \think\Loader::model('Person','model');
        $this->eventCtr = \think\Loader::controller('Person','event');
        $this->view->engine->layout('layout/layout');
    }

    public function lst()
    {
        $request = Request::instance();
        $page = isset($_GET['page']) ? $_GET['page'] : 1 ;
        $where = array(
            'name'=>$request->param('name'),
            'mobile'=>$request->param('mobile')
        );
        $data = $this->eventCtr->lst($page,0,$where);
        $this->assign(
            'data',$data['data']
        );
        $this->assign('pageData',$data['page']);

        // 设置页面中的信息
        $this->assign(array(
            '_page_btn_name' => '添加人员',
            '_page_btn_link' => url('add'),
        ));


        return $this->fetch();
    }



    public function add()
    {
        $request = Request::instance();
        if($request->isPost()){
            //print_r($request->param());
            $res = $this->eventCtr->add($request->param());
            die(json_encode($res));
        }elseif($request->isGet()){
            return $this->fetch();
        }


    }
    public function edit()
    {
        $request = Request::instance();
        if($request->isPost()){
            $id = $request->param('id');
            $data = $request->param();
            $res = $this->eventCtr->edit($id,$data);
            die(json_encode($res));
        }elseif($request->isGet()){
            $id = $request->param('id');
            $data = $this->eventCtr->row($id);
            $this->assign('data',$data);
            return $this->fetch();
        }

    }
    public function delete()
    {
        $request = Request::instance();
        $res = $this->eventCtr->del($request->param('id'));
        die(json_encode($res));
    }




}
