<?php
// +----------------------------------------------------------------------
// | @date: 2017/11/22 - 17:20
// +----------------------------------------------------------------------
// | @author：Ulex
// +----------------------------------------------------------------------
// | @desc：
// +----------------------------------------------------------------------
namespace app\admin\Controller;
use think\Request;

class Privilege extends Base
{
    protected $model = null;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->model = \think\Loader::model('Privilege');
        $this->view->engine->layout('layout/layout');
    }

    public function lst()
    {
        // 设置页面中的信息
        $this->assign(array(
            '_page_btn_name' => '添加权限',
            '_page_btn_link' => url('add'),
            '_page_btn_refresh' => TRUE,
        ));
        return $this->fetch();
    }


    /**
     * 权限列表接口
     */
    public function priv_list(){
        $model = $this->model;
        $data = $model->getTree();
        die(json_encode($data));
    }


    public function add(Request $request)
    {
//        var_dump(I('post.'));exit();
        if($request->isPost())
        {
            $model = $this->model;
            if($model->create(I('post.'), 1))
            {
                if($id = $model->add())
                {
                    $this->success('添加成功！', U('lst?p='.I('get.p')));
                    exit;
                }
            }
            $this->error($model->getError());
        }else{

            return $this->fetch();
        }

    }
    public function edit()
    {
        $id = I('get.id');
        if(IS_POST)
        {
            $model = D('Privilege');
            if($model->create(I('post.'), 2))
            {
                if($model->save() !== FALSE)
                {
                    $this->success('修改成功！', U('lst', array('p' => I('get.p', 1))));
                    exit;
                }
            }
            $this->error($model->getError());
        }
        $model = M('Privilege');
        $data = $model->find($id);
        $this->assign('data', $data);
        $parentModel = D('Privilege');
        $parentData = $parentModel->getTree();
        $children = $parentModel->getChildren($id);
        $this->assign(array(
            'parentData' => $parentData,
            'children' => $children,
        ));

        // 设置页面中的信息
        $this->assign(array(
            '_page_btn_name' => '权限列表',
            '_page_btn_link' => U('lst'),
        ));
        $this->display();
    }
    public function delete()
    {
        $model = D('Privilege');
        if($model->delete(I('get.id', 0)) !== FALSE)
        {
            $this->success('删除成功！', U('lst', array('p' => I('get.p', 1))));
            exit;
        }
        else
        {
            $this->error($model->getError());
        }
    }
}