<?php
// +----------------------------------------------------------------------
// | @date: 2018/06/14
// +----------------------------------------------------------------------
// | @author：weipinglee
// +----------------------------------------------------------------------
// | @desc：
// +----------------------------------------------------------------------
namespace app\admin\Controller;

use think\Request;

class Role extends Base{


    protected $model = null;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->model = \think\Loader::model('Role','service');
        $this->view->engine->layout('layout/layout');
    }


    public function lst()
    {
        $model = $this->model;
        $data = $model->lists();
//		dump($data);exit();
        $this->assign(array(
            'data' => $data['data'],
            'pageData' => $data['page']
        ));

        // 设置页面中的信息
        $this->assign(array(
            '_page_btn_name' => '添加角色',
            '_page_btn_link' => url('add'),
            '_page_btn_refresh' => TRUE,
        ));
        return $this->fetch();
    }


    public function add(Request $request)
    {
        if($request->isPost())
        {
//			dump($_POST);exit();
            $params = $request->param();
            $data = array(
                'role_name'=>$params['role_name'],
                'pri_id' => $params['pri_id']
            );
            $res = $this->model->add($data);
            die(json_encode($res));
        }else{
            $this->assign(array(
                '_page_btn_name' => '角色列表',
                '_page_btn_link' => url('lst'),
            ));
            return $this->fetch();

        }


    }

    /**
     * @name：edit
     * @author：Ulex
     * @desc：
     */
    public function edit(Request $request)
    {
        if($request->isPost())
        {
            $model = D('Role');
//    		var_dump(I('post.'));exit();
            if($model->create(I('post.'), 2))
            {
                if($model->save() !== FALSE)
                {
                    $this->success('修改成功！', U('lst'));
                    exit;
                }
            }
            $this->error($model->getError());
        }else{
            $role_name = D('Role')->find($id);
            //取出所有的权限
            $priModel = D('privilege');
            $priData = $priModel->getTree();
            $this->assign('priData', $priData);
            //取出用户权限
            $user_priData = $priModel->getPriByUserId($id);
            $this->assign('user_priData', $user_priData);


            $this->assign('role_name', $role_name);
//        var_dump($priData,$user_priData);exit();
            // 设置页面中的信息
            $this->assign(array(
                '_page_btn_name' => '角色列表',
                '_page_btn_link' => U('lst'),
            ));
            $this->display();
        }

    }
    public function delete()
    {

    }
}