<?php
// +----------------------------------------------------------------------
// | @date: 2018/06/14
// +----------------------------------------------------------------------
// | @author：weipinglee
// +----------------------------------------------------------------------
// | @desc：
// +----------------------------------------------------------------------
namespace app\admin\Controller;

use think\Request;

class Role extends Base{


    protected $model = null;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->model = \think\Loader::model('Role','service');
        $this->view->engine->layout('layout/layout');
    }


    public function lst()
    {
        $model = $this->model;
        $data = $model->lists();
//		dump($data);exit();
        $this->assign(array(
            'data' => $data['data'],
            'pageData' => $data['page']
        ));

        // 设置页面中的信息
        $this->assign(array(
            '_page_btn_name' => '添加角色',
            '_page_btn_link' => url('add'),
            '_page_btn_refresh' => TRUE,
        ));
        return $this->fetch();
    }


    public function add(Request $request)
    {
        if($request->isPost())
        {
//			dump($_POST);exit();
            $params = $request->param();
            $data = array(
                'role_name'=>$params['role_name'],
                'pri_id' => $params['pri_id']
            );
            $res = $this->model->add($data);
            die(json_encode($res));
        }else{
            $this->assign(array(
                '_page_btn_name' => '角色列表',
                '_page_btn_link' => url('lst'),
            ));
            return $this->fetch();

        }


    }

    /**
     * @name：edit
     * @author：Ulex
     * @desc：
     */
    public function edit(Request $request)
    {
        if($request->isPost())
        {
            $params = $request->param();
            $id = $params['id'];
            $data = array(
                'role_name'=>$params['role_name'],
                'pri_id' => $params['pri_id']
            );
            die(json_encode($this->model->edit($id,$data)));
        }else{

            $id = $request->param('id');
            $this->assign(array(
                'id'=>$id,
                '_page_btn_name' => '角色列表',
                '_page_btn_link' => url('lst'),
            ));
            return $this->fetch();
        }

    }


    /**
     * 获取一条角色数据，包含权限
     * @param Request $request
     */
    public function oneRole(Request $request){
        $id = $request->param('id');
        die(json_encode($this->model->row($id)));
    }
}